"""
Seed HealthOS API users into Postgres.

Local demo users (generated passwords, printed once):

  python -m scripts.seed_users --demo

Explicit local user (development only):

  python -m scripts.seed_users --user username:password:ADMIN:00000000-0000-4000-8000-000000000001

Do not reuse generated demo passwords outside your local machine.
"""

from __future__ import annotations

import argparse
import asyncio
import os
import secrets
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable
from uuid import UUID

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from api.auth.passwords import hash_password
from api.settings import Settings
from db.enums import UserRole
from db.models.user import User
from db.session import create_engine, create_session_factory

DEMO_TENANT_ID = UUID("00000000-0000-4000-8000-000000000001")
CREDENTIALS_FILE = Path(ROOT) / ".local-demo-credentials"


@dataclass(frozen=True)
class UserSeed:
    username: str
    password: str
    role: UserRole
    tenant_id: UUID


def parse_user_spec(value: str) -> UserSeed:
    parts = value.split(":")
    if len(parts) != 4:
        raise argparse.ArgumentTypeError(
            "--user must be in the form username:password:role:tenant_id"
        )

    username, password, role_value, tenant_id = parts
    if not username:
        raise argparse.ArgumentTypeError("username must not be empty")
    if not password:
        raise argparse.ArgumentTypeError("password must not be empty")
    try:
        role = UserRole(role_value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            f"invalid role {role_value!r}; valid roles are {[r.value for r in UserRole]}"
        ) from exc
    try:
        tenant_uuid = UUID(tenant_id)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(f"invalid tenant_id {tenant_id!r}") from exc

    return UserSeed(
        username=username,
        password=password,
        role=role,
        tenant_id=tenant_uuid,
    )


def build_demo_users() -> list[UserSeed]:
    """Generate local-only admin and clinician users with fresh passwords."""
    return [
        UserSeed(
            username="admin",
            password=secrets.token_urlsafe(12),
            role=UserRole.ADMIN,
            tenant_id=DEMO_TENANT_ID,
        ),
        UserSeed(
            username="clinician",
            password=secrets.token_urlsafe(12),
            role=UserRole.CLINICIAN,
            tenant_id=DEMO_TENANT_ID,
        ),
    ]


def write_local_credentials(users: Iterable[UserSeed]) -> None:
    """Write generated passwords to a gitignored local file. Never commit it."""
    lines = [
        "LOCAL DEVELOPMENT ONLY — NEVER USE IN PRODUCTION",
        "Generated by: python -m scripts.seed_users --demo",
        "Re-running --demo replaces these passwords.",
        "",
    ]
    for user in users:
        lines.append(f"{user.username} {user.role.value} {user.password}")
    CREDENTIALS_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


async def seed_users(users: Iterable[UserSeed]) -> None:
    settings = Settings()
    engine = create_engine(settings)
    factory = create_session_factory(engine)

    async with factory() as session:
        for user in users:
            await create_or_update_user(session, user)
        await session.commit()

    await engine.dispose()


async def create_or_update_user(session: AsyncSession, user: UserSeed) -> None:
    result = await session.execute(select(User).where(User.username == user.username))
    existing = result.scalar_one_or_none()
    hashed = hash_password(user.password)

    if existing is None:
        session.add(
            User(
                username=user.username,
                password_hash=hashed,
                role=user.role,
                tenant_id=user.tenant_id,
                is_active=True,
            )
        )
        print(f"Created user {user.username!r} ({user.role.value})")
    else:
        existing.password_hash = hashed
        existing.role = user.role
        existing.tenant_id = user.tenant_id
        existing.is_active = True
        print(f"Updated user {user.username!r} ({user.role.value})")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Seed or update HealthOS API users in Postgres."
    )

    parser.add_argument(
        "--user",
        type=parse_user_spec,
        action="append",
        help=(
            "User spec in the form username:password:role:tenant_id. "
            "Repeatable. For local development only."
        ),
    )
    parser.add_argument(
        "--demo",
        action="store_true",
        help=(
            "Create or rotate local demo admin and clinician users. "
            "Passwords are generated and printed once. Not for production."
        ),
    )
    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    seeds: list[UserSeed] = []
    demo_seeds: list[UserSeed] = []
    if args.demo:
        demo_seeds = build_demo_users()
        seeds.extend(demo_seeds)

    if args.user:
        seeds.extend(args.user)

    if not seeds:
        parser.error("provide --demo or at least one --user")

    asyncio.run(seed_users(seeds))

    if demo_seeds:
        write_local_credentials(demo_seeds)
        print("")
        print("LOCAL DEVELOPMENT ONLY — NEVER USE IN PRODUCTION")
        print("Demo passwords (shown once; also written to .local-demo-credentials):")
        for user in demo_seeds:
            print(f"  {user.username} / {user.password}")


if __name__ == "__main__":
    main()
